### ISSUE TITLE
Android Devices Not recognizing document viewer as OXPS doc default

### ISSUE THREAD

**Issue by mblack2004usa** [SufficientlySecure/document-viewer#239]
Document viewer works great for viewing OXPS documents. However, Android OS is not recognizing DOCUMENT Viewer as a default app for OXPS documents. Anytime I receive on in an email with an OXPS document and click on it. It says no compatible viewer found. I have to save the attachment then open document viewer to see it.  I tried on an android 6 OS and 7 OS. Same result. Also tried different email apps (GMAIL and Blue Mail) Same result.  Even some file managers don't recognize it as default viewer for OXPS.

**Comment by ericwa** [comment]
Hmm, I wonder if it is specific to certain XPS files?

I'm currently running MIUI 8.1 (Android 6.0.1). I tried visiting this page in Chrome and downloading the ECMA-388.xps file:
https://www.ecma-international.org/publications/standards/Ecma-388.htm

Document Viewer was offered as the first choice in the "Open with" dialog.
I also downloaded that file and emailed it to myself with GMail, opened the attachment  and DV was also offered as a viewer.

Do you mind checking if you can reproduce with that XPS file, or post another one that shows the problem? Maybe I need to test on stock android?

**Comment by mblack2004usa** [comment]
OK the .xps extension file works fine. I tested it with no problems. Looks
like it's only a problem with files that have .oops extension. Try one of
those.

**Comment by mblack2004usa** [comment]
Sorry stupid auto correct. Meant .oxps extention.

**Comment by ericwa** [comment]
Ah, thanks, I think I see the problem..

- Opening a .xps file from Gmail, the intent has the `application/vnd.ms-xpsdocument` MIME type, which DV indicates it can open.
- When I open a .oxps attachment, however, the MIME type is `application/octet-stream`. I modified DV to accept any mime type to be able to see the intent:
 
> Intent { act=android.intent.action.VIEW dat=content://gmail-ls/XXX@gmail.com/messages/XXX/attachments/0.1/BEST/false typ=application/octet-stream flg=... cmp=org.sufficientlysecure.viewer/org.ebookdroid.ui.viewer.ViewerActivity }

So, unfortunately there is nothing in the intent that indicates it's a file DV can display.. I'm not sure if there is any way to fix this on DV's side; it looks like a bug in the Gmail app. I don't think we want to make DV accept the `application/octet-stream` MIME type, otherwise Document Viewer will try to open every kind of email attachment.

**Comment by mblack2004usa** [comment]
Makes sense. It's happening with multiple email apps so they all must be
handling it the same way.  .oxps files are fairly rare anyway. I can save
it out then the viewer sees it so not a major issue.
